[azure_credentials]
tenant_id = "02045b3b-9790-4008-b83c-d155576e6c7e"
client_id = "1c29e7f1-aef9-4c3d-a4df-fd3f11c8bf3a"

[get_secret_keyvault]
tenant_id = "02045b3b-9790-4008-b83c-d155576e6c7e"
client_id = "7c8b5b95-0919-42b5-8c89-924c20d45ef0"
client_secret = "2gX8Q~VFWSQIso5ZgHiq4~9L~InITOJO6pMSrbbT"
client_secret_name = "db-client-secret"

[azure_storage]
account_name = "gfrdatastorage"
container_name = "global-fashion-retails-data"
stores_file_path = "gold/stores/part-00000-f608fe67-04e6-4700-a0d1-19290aedcebf.c000.snappy.parquet"

[sql_connection]
SERVER = "global-fashion-retails.database.windows.net"
DATABASE = "gfr-data"
USERNAME = "mdyasser42"
PASSWORD = "Mm332211"