[azure_credentials]
tenant_id = "02045b3b-9790-4008-b83c-d155576e6c7e"
client_id = "1c29e7f1-aef9-4c3d-a4df-fd3f11c8bf3a"
client_secret = "YQ28Q~lZTFse-aQHPOqkeoKEcb7f4v5kqJ8gvcmb"

[azure_storage]
account_name = "gfrdatastorage"
container_name = "global-fashion-retails-data"
stores_file_path = "gold/stores/part-00000-f608fe67-04e6-4700-a0d1-19290aedcebf.c000.snappy.parquet"
products_file_path = "gold/products/part-00000-a3f8d7bf-9d2f-40a4-9d97-c71fba7f7e73.c000.snappy.parquet"
customer_filepath = "gold/customers/part-00000-2bbf662b-cab3-4bbd-b4fc-cbbe0da81410.c000.snappy.parquet"
transactions_filepath = "gold/invoice_line_items/part-00000-027b79af-fe50-48f8-b3f7-4c7e4cdb64fd.c000.snappy.parquet"

[sql_connection]
SERVER = "global-fashion-retails.database.windows.net"
DATABASE = "gfr-data"
USERNAME = "mdyasser42"
PASSWORD = "Mm332211"