[azure_credentials]
tenant_id = "02045b3b-9790-4008-b83c-d155576e6c7e"
client_id = "1c29e7f1-aef9-4c3d-a4df-fd3f11c8bf3a"
client_secret = "YQ28Q~lZTFse-aQHPOqkeoKEcb7f4v5kqJ8gvcmb"

[azure_storage]
account_name = "gfrdatastorage"